services:
  - type: web
    name: unica-doors
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_ADMIN_LOGIN
        value: admin
      - key: SEED_ADMIN_PASSWORD
        sync: false
      - key: TZ_OFFSET_MINUTES
        value: "360"
